#!/usr/bin/env python3
"""Acceptance harness for the Phase-6 improve loop — the deterministic judge.

Phase 6 (docs/plans/2026-07-13-phase-6-improve-loop.md) lets a writer agent
propose ONE candidate change to the target's key-less determ suite per
iteration. Whether the candidate is kept is decided HERE, by committed code —
never by an LLM's opinion (Goldene Regel 2). This module implements the 6a
subset of the acceptance rule:

  D1  Reproducibility — the suite with the candidate applied runs twice with
      an identical per-test outcome. A differing pair is discarded as
      ``flaky``: a flaky assert would poison the deterministic ground truth.
  D2  No false positive — every test that is red with the candidate applied
      was already red in the baseline (current target HEAD, no candidate).
      A candidate that turns green tests red, or whose own new asserts fail
      on HEAD, is discarded as ``false-positive``.
  D3  Added value (Phase 6b) — a candidate that proves nothing new is
      discarded as ``redundant``. Two modes (``--coverage-mode``):

      mutation     the strong form. Against a pool of mutant diffs of the
                   target source (``--mutants-dir``, generated by mutmut /
                   cosmic-ray / any tool — the harness only applies patches),
                   the existing suite's kill status is computed once per
                   target SHA and cached. A candidate is kept only if it
                   kills at least one mutant that SURVIVES the existing
                   suite. A semantic duplicate of an existing assert kills
                   nothing new -> ``redundant``.
      schema-path  D3-lite for hosts without a mutation budget (the Pi-5
                   default): the candidate must reference at least one
                   ``schemas/*.json`` path that no existing file under
                   ``promptfoo/`` references. Weaker but deterministic and
                   free of extra suite runs.
      off          skip D3 (D1/D2 only — for incremental rollout).

Two further checks are properties of the candidate itself, so they are also
discards, not hard failures: a patch that does not apply (``invalid``) and a
patch touching anything outside ``promptfoo/`` (``out-of-scope`` — the single
editable surface, enforced in the harness and not just in IMPROVE.md).

Everything else — the runner crashing, unparseable results, an empty suite, a
baseline that is itself flaky on HEAD — is an infrastructure HARD failure:
exit 1, never counted as a discard (an aborted run is not a result).

Every judged candidate is appended to the gitignored, append-only journal
``.audit/experiments.jsonl`` (ts, candidate_sha, target_sha, verdict, grund,
dauer_s) — the autoresearch-style experiment log the morning PR embeds.

Exit codes (the contract with improve-loop.sh, Phase 6c — mirrors the repo's
0 green / 2 findings / 1 hard-fail convention):

  judge     -> 0  keep      commit the candidate onto improve/<datum>
            -> 2  discard   revert; the journal carries the grund
            -> 1  hard-fail abort the whole loop iteration
  baseline  -> 0  baseline computed (or cached) and reproducible
            -> 1  the existing suite is not deterministic on HEAD — that is a
                  nightly finding, not an improve problem (Invariante 5)

The suite runner is injected (``--runner``), never hardcoded: the harness
invokes ``<runner> <config> <output.json>`` in the target checkout and reads
promptfoo-style JSON from ``<output.json>``. Phase 6c supplies the pinned
promptfoo wrapper; the tests supply a tiny fake. Stdlib-only, and the only
side effects are the journal, the baseline cache, and the (always reverted)
candidate application — matching scripts/budget_guard.py.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shlex
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

EXIT_KEEP = 0
EXIT_HARD_FAIL = 1
EXIT_DISCARD = 2

# The single editable surface of the improve loop (Phase-6 Invariante 4).
EDITABLE_PREFIX = "promptfoo/"

COVERAGE_MODES = ("off", "schema-path", "mutation")

# D3-lite: what counts as "referencing a schema path". Matches the drift
# detector's layout (schemas/<name>.json, incl. subdirectories).
SCHEMA_REF_RE = re.compile(r"schemas/[A-Za-z0-9_.\-/]*\.json")

# Runner exit codes that mean "the suite ran" (results JSON is authoritative):
# 0 = all pass, 1 = generic failure, 100 = promptfoo's default failed-eval code.
_RUNNER_RAN = {0, 1, 100}

_JOURNAL_SCHEMA = 1
_BASELINE_SCHEMA = 1


class Discard(Exception):
    """The candidate is rejected — a verdict about the candidate (exit 2)."""

    def __init__(self, grund: str, detail: str = "") -> None:
        super().__init__(detail or grund)
        self.grund = grund


class HardFail(Exception):
    """The judgement could not be carried out — never a verdict (exit 1)."""


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _sha256_short(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:12]


def _git(target_dir: Path, *argv: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(target_dir), *argv],
        capture_output=True,
        text=True,
        check=False,
    )


def target_sha(target_dir: Path) -> str:
    cp = _git(target_dir, "rev-parse", "--short", "HEAD")
    return cp.stdout.strip() if cp.returncode == 0 and cp.stdout.strip() else "unknown"


# --- candidate patch handling -------------------------------------------------


def candidate_paths(target_dir: Path, patch: Path) -> list[str]:
    """Paths touched by the candidate, via ``git apply --numstat`` (no apply).

    An unparseable patch or an empty diff is a property of the candidate ->
    Discard("invalid"), not a hard failure.
    """
    cp = _git(target_dir, "apply", "--numstat", str(patch))
    if cp.returncode != 0:
        raise Discard("invalid", f"patch does not parse: {cp.stderr.strip()}")
    paths: list[str] = []
    for line in cp.stdout.splitlines():
        parts = line.split("\t")
        if len(parts) >= 3 and parts[2]:
            paths.append(parts[2])
    if not paths:
        raise Discard("invalid", "empty diff — nothing to judge")
    return paths


def check_scope(paths: list[str]) -> None:
    outside = [p for p in paths if not p.startswith(EDITABLE_PREFIX)]
    if outside:
        raise Discard(
            "out-of-scope",
            f"candidate touches files outside {EDITABLE_PREFIX}: {', '.join(outside)}",
        )


def apply_candidate(target_dir: Path, patch: Path) -> None:
    cp = _git(target_dir, "apply", "--check", str(patch))
    if cp.returncode != 0:
        raise Discard("invalid", f"patch does not apply: {cp.stderr.strip()}")
    cp = _git(target_dir, "apply", str(patch))
    if cp.returncode != 0:
        raise Discard("invalid", f"patch does not apply: {cp.stderr.strip()}")


def revert_candidate(target_dir: Path, patch: Path) -> None:
    cp = _git(target_dir, "apply", "-R", str(patch))
    if cp.returncode != 0:
        # A checkout left dirty would contaminate every later judgement.
        raise HardFail(
            f"could not revert candidate — target checkout is DIRTY: {cp.stderr.strip()}"
        )


# --- suite execution ------------------------------------------------------------


def _results_map(out_json: Path) -> dict[str, bool]:
    """Per-test outcome map from a promptfoo-style ``--output`` JSON file.

    Tolerates both the wrapped (``{"results": {"results": [...]}}``) and the
    bare (``{"results": [...]}``) shape, like budget_guard.tokens_from_promptfoo.
    """
    try:
        data = json.loads(out_json.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise HardFail(f"runner produced no parseable results JSON: {exc}") from exc
    block: Any = data.get("results", data) if isinstance(data, dict) else data
    if isinstance(block, dict):
        block = block.get("results", [])
    if not isinstance(block, list):
        raise HardFail("results JSON has no test list")
    outcomes: dict[str, bool] = {}
    for i, entry in enumerate(block):
        if not isinstance(entry, dict):
            raise HardFail(f"results entry #{i} is not an object")
        key = entry.get("description")
        if key is None:
            key = entry.get("testIdx")
        if key is None:
            key = i
        key = str(key)
        if key in outcomes:  # duplicate labels must not shadow each other
            key = f"{key}#{i}"
        outcomes[key] = bool(entry.get("success"))
    if not outcomes:
        # Fail closed: an empty suite silently "passing twice" is no evidence.
        raise HardFail("suite produced zero test results")
    return outcomes


def run_suite(
    runner: list[str], target_dir: Path, config: str, out_json: Path
) -> dict[str, bool]:
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.unlink(missing_ok=True)
    try:
        cp = subprocess.run(
            [*runner, config, str(out_json)],
            cwd=str(target_dir),
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        raise HardFail(f"runner could not be executed: {exc}") from exc
    if cp.returncode not in _RUNNER_RAN:
        raise HardFail(
            f"runner failed (exit {cp.returncode}): {cp.stderr.strip()[-500:]}"
        )
    return _results_map(out_json)


def run_suite_twice(
    runner: list[str], target_dir: Path, config: str, work_dir: Path, tag: str
) -> tuple[dict[str, bool], dict[str, bool]]:
    run1 = run_suite(runner, target_dir, config, work_dir / f"{tag}-run1.json")
    run2 = run_suite(runner, target_dir, config, work_dir / f"{tag}-run2.json")
    return run1, run2


# --- baseline (existing suite on target HEAD, no candidate) ---------------------


def baseline_cache_path(journal: Path, sha: str) -> Path:
    return journal.parent / f"improve-baseline-{sha}.json"


def load_baseline(cache: Path, sha: str) -> dict[str, bool] | None:
    if not cache.exists():
        return None
    try:
        data = json.loads(cache.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if (
        not isinstance(data, dict)
        or data.get("schema") != _BASELINE_SCHEMA
        or data.get("target_sha") != sha
        or not isinstance(data.get("tests"), dict)
    ):
        return None
    return {str(k): bool(v) for k, v in data["tests"].items()}


def compute_baseline(
    runner: list[str], target_dir: Path, config: str, cache: Path, sha: str
) -> dict[str, bool]:
    run1, run2 = run_suite_twice(runner, target_dir, config, cache.parent, "baseline")
    if run1 != run2:
        # The EXISTING suite is not deterministic on HEAD. That is a nightly
        # finding about the target, not a property of any candidate: abort.
        raise HardFail(
            "baseline suite is not reproducible on target HEAD (two runs "
            "differ) — fix the existing suite before judging candidates"
        )
    cache.parent.mkdir(parents=True, exist_ok=True)
    cache.write_text(
        json.dumps(
            {
                "schema": _BASELINE_SCHEMA,
                "target_sha": sha,
                "computed_at": _now_iso(),
                "tests": run1,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return run1


# --- D3: added value (Phase 6b) --------------------------------------------------

# Mutant patches are infrastructure, not candidates: one that does not apply
# or revert is a broken pool / dirty checkout -> HardFail, never a verdict.


def _apply_mutant(target_dir: Path, patch: Path) -> None:
    for argv in (("apply", "--check", str(patch)), ("apply", str(patch))):
        cp = _git(target_dir, *argv)
        if cp.returncode != 0:
            raise HardFail(
                f"mutant {patch.name} does not apply: {cp.stderr.strip()}"
            )


def _revert_mutant(target_dir: Path, patch: Path) -> None:
    cp = _git(target_dir, "apply", "-R", str(patch))
    if cp.returncode != 0:
        raise HardFail(
            f"could not revert mutant {patch.name} — target checkout is DIRTY: "
            f"{cp.stderr.strip()}"
        )


def _new_reds(reference: dict[str, bool], run: dict[str, bool]) -> bool:
    """True iff some test green in `reference` is not green in `run` (a test
    that disappears under a mutant also counts — any deviation is detection)."""
    return any(ok and run.get(key) is not True for key, ok in reference.items())


def list_mutants(mutants_dir: Path) -> list[Path]:
    patches = sorted(mutants_dir.glob("*.patch")) if mutants_dir.is_dir() else []
    if not patches:
        # Fail closed: without mutants, "added value" cannot be measured — a
        # silent keep-everything would hollow out D3.
        raise HardFail(
            f"coverage-mode mutation needs a mutant pool, none found in "
            f"{mutants_dir} (*.patch)"
        )
    return patches


def mutants_cache_path(journal: Path, sha: str) -> Path:
    return journal.parent / f"improve-mutants-{sha}.json"


def load_mutants_baseline(cache: Path, sha: str) -> dict[str, str] | None:
    if not cache.exists():
        return None
    try:
        data = json.loads(cache.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if (
        not isinstance(data, dict)
        or data.get("schema") != _BASELINE_SCHEMA
        or data.get("target_sha") != sha
        or not isinstance(data.get("mutants"), dict)
    ):
        return None
    return {str(k): str(v) for k, v in data["mutants"].items()}


def compute_mutants_baseline(
    runner: list[str],
    target_dir: Path,
    config: str,
    mutants_dir: Path,
    clean_baseline: dict[str, bool],
    cache: Path,
    sha: str,
) -> dict[str, str]:
    """Which mutants does the EXISTING suite kill? One suite run per mutant,
    cached per target SHA (the SHA covers both source and suite)."""
    status: dict[str, str] = {}
    for patch in list_mutants(mutants_dir):
        _apply_mutant(target_dir, patch)
        try:
            run = run_suite(
                runner, target_dir, config, cache.parent / f"mutant-{patch.stem}.json"
            )
        finally:
            _revert_mutant(target_dir, patch)
        status[patch.name] = "killed" if _new_reds(clean_baseline, run) else "survived"
    cache.parent.mkdir(parents=True, exist_ok=True)
    cache.write_text(
        json.dumps(
            {
                "schema": _BASELINE_SCHEMA,
                "target_sha": sha,
                "computed_at": _now_iso(),
                "mutants": status,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return status


def d3_mutation(
    runner: list[str],
    target_dir: Path,
    config: str,
    candidate: Path,
    mutants_dir: Path,
    mutants_status: dict[str, str],
    candidate_clean: dict[str, bool],
    work_dir: Path,
) -> str:
    """Return the name of the first SURVIVING mutant the candidate kills, or
    raise Discard("redundant"). `candidate_clean` is the candidate's run on
    the unmutated target (already proven green-or-preexisting-red by D2)."""
    surviving = [name for name, s in sorted(mutants_status.items()) if s == "survived"]
    if not surviving:
        # The existing suite already kills the whole pool — this pool cannot
        # distinguish added value. Regenerating mutants is an operator task.
        raise HardFail(
            "no surviving mutants in the pool — it cannot measure added "
            "value; regenerate a stronger mutant pool"
        )
    for name in surviving:
        _apply_mutant(target_dir, mutants_dir / name)
        try:
            try:
                apply_candidate(target_dir, candidate)
            except Discard as exc:
                # It applied on the clean tree (D1/D2 ran), so a conflict here
                # is a mutant/candidate overlap — infrastructure, not verdict.
                raise HardFail(
                    f"candidate conflicts with mutant {name}: {exc}"
                ) from exc
            try:
                run = run_suite(
                    runner,
                    target_dir,
                    config,
                    work_dir / f"candidate-vs-{Path(name).stem}.json",
                )
            finally:
                revert_candidate(target_dir, candidate)
        finally:
            _revert_mutant(target_dir, mutants_dir / name)
        if _new_reds(candidate_clean, run):
            return name
    raise Discard(
        "redundant",
        f"kills none of the {len(surviving)} mutants surviving the existing suite",
    )


def _added_lines(patch: Path) -> str:
    return "\n".join(
        line[1:]
        for line in patch.read_text(encoding="utf-8", errors="replace").splitlines()
        if line.startswith("+") and not line.startswith("+++")
    )


def existing_schema_refs(target_dir: Path) -> set[str]:
    refs: set[str] = set()
    root = target_dir / EDITABLE_PREFIX
    if root.is_dir():
        for f in root.rglob("*"):
            if not f.is_file():
                continue
            try:
                refs.update(SCHEMA_REF_RE.findall(f.read_text(encoding="utf-8")))
            except (OSError, UnicodeDecodeError):
                continue  # binary / unreadable — cannot carry an assert
    return refs


def d3_schema_path(target_dir: Path, candidate: Path) -> list[str]:
    """D3-lite: the candidate must reference a schemas/*.json path that no
    existing file under promptfoo/ references. Returns the new refs."""
    added = set(SCHEMA_REF_RE.findall(_added_lines(candidate)))
    new = sorted(added - existing_schema_refs(target_dir))
    if not new:
        raise Discard(
            "redundant",
            "adds no schema path that the existing suite does not already "
            "reference (D3-lite; use --coverage-mode mutation for the strong check)",
        )
    return new


# --- journal ---------------------------------------------------------------------


def journal_append(journal: Path, entry: dict[str, Any]) -> None:
    journal.parent.mkdir(parents=True, exist_ok=True)
    with journal.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(entry, sort_keys=True) + "\n")


# --- commands ---------------------------------------------------------------------


def cmd_baseline(args: argparse.Namespace) -> int:
    target_dir = Path(args.target_dir)
    journal = Path(args.journal)
    sha = target_sha(target_dir)
    cache = Path(args.cache) if args.cache else baseline_cache_path(journal, sha)
    runner = shlex.split(args.runner)
    try:
        tests = load_baseline(cache, sha)
        if tests is not None:
            print(
                f"IMPROVE: baseline cached for {sha} ({len(tests)} tests)", flush=True
            )
        else:
            tests = compute_baseline(runner, target_dir, args.config, cache, sha)
            print(
                f"IMPROVE: baseline computed for {sha} ({len(tests)} tests)",
                flush=True,
            )
        # In mutation mode, precompute the (expensive) kill map up front so the
        # loop pays for it once per target SHA, not inside the first judgement.
        if args.coverage_mode == "mutation":
            mcache = mutants_cache_path(journal, sha)
            status = load_mutants_baseline(mcache, sha)
            if status is None:
                status = compute_mutants_baseline(
                    runner,
                    target_dir,
                    args.config,
                    Path(args.mutants_dir),
                    tests,
                    mcache,
                    sha,
                )
            surviving = sum(1 for s in status.values() if s == "survived")
            print(
                f"IMPROVE: mutants baseline for {sha}: {len(status)} mutants, "
                f"{surviving} surviving",
                flush=True,
            )
    except HardFail as exc:
        print(f"IMPROVE: HARD FAIL — {exc}", flush=True)
        return EXIT_HARD_FAIL
    return 0


def cmd_judge(args: argparse.Namespace) -> int:
    t0 = time.monotonic()
    target_dir = Path(args.target_dir)
    journal = Path(args.journal)
    patch = Path(args.candidate)
    runner = shlex.split(args.runner)
    sha = target_sha(target_dir)
    cache = Path(args.cache) if args.cache else baseline_cache_path(journal, sha)

    entry: dict[str, Any] = {
        "schema": _JOURNAL_SCHEMA,
        "ts": _now_iso(),
        "candidate": patch.name,
        "candidate_sha": _sha256_short(patch) if patch.exists() else "missing",
        "target_sha": sha,
        "coverage_mode": args.coverage_mode,
        "verdict": "hard-fail",
        "grund": None,
        "dauer_s": 0.0,
        "tests": None,
    }

    def finish(verdict: str, grund: str | None, rc: int) -> int:
        entry["verdict"] = verdict
        entry["grund"] = grund
        entry["dauer_s"] = round(time.monotonic() - t0, 3)
        journal_append(journal, entry)
        label = f" ({grund})" if grund else ""
        print(f"IMPROVE: {verdict}{label} — {patch.name} @ {sha}", flush=True)
        return rc

    try:
        if not patch.exists():
            raise HardFail(f"candidate patch not found: {patch}")

        check_scope(candidate_paths(target_dir, patch))

        baseline = load_baseline(cache, sha)
        if baseline is None:
            baseline = compute_baseline(runner, target_dir, args.config, cache, sha)

        apply_candidate(target_dir, patch)
        try:
            run1, run2 = run_suite_twice(
                runner, target_dir, args.config, cache.parent, "candidate"
            )
        finally:
            revert_candidate(target_dir, patch)

        entry["tests"] = {
            "total": len(run1),
            "failed": sum(1 for ok in run1.values() if not ok),
        }

        # D1 — reproducibility: two runs with the candidate must agree exactly.
        if run1 != run2:
            differing = sorted(k for k in run1 if run1[k] != run2.get(k))
            raise Discard(
                "flaky", f"non-reproducible outcome for: {', '.join(differing)}"
            )

        # D2 — no false positive: red-with-candidate is only acceptable where
        # the baseline was already red (a real, pre-existing nightly finding).
        false_pos = sorted(
            k for k, ok in run1.items() if not ok and baseline.get(k, True)
        )
        if false_pos:
            raise Discard(
                "false-positive", f"red on target HEAD: {', '.join(false_pos)}"
            )

        # D3 — added value: a candidate that proves nothing new is redundant.
        if args.coverage_mode == "schema-path":
            entry["new_schema_refs"] = d3_schema_path(target_dir, patch)
        elif args.coverage_mode == "mutation":
            mcache = mutants_cache_path(journal, sha)
            status = load_mutants_baseline(mcache, sha)
            if status is None:
                status = compute_mutants_baseline(
                    runner,
                    target_dir,
                    args.config,
                    Path(args.mutants_dir),
                    baseline,
                    mcache,
                    sha,
                )
            entry["killed_mutant"] = d3_mutation(
                runner,
                target_dir,
                args.config,
                patch,
                Path(args.mutants_dir),
                status,
                run1,
                mcache.parent,
            )

    except Discard as exc:
        print(f"IMPROVE: discard detail — {exc}", flush=True)
        return finish("discard", exc.grund, EXIT_DISCARD)
    except HardFail as exc:
        print(f"IMPROVE: HARD FAIL — {exc}", flush=True)
        return finish("hard-fail", str(exc), EXIT_HARD_FAIL)

    return finish("keep", None, EXIT_KEEP)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--journal",
        default=os.environ.get("IMPROVE_JOURNAL", ".audit/experiments.jsonl"),
        help="append-only experiments journal (gitignored)",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument(
        "--target-dir", required=True, help="target checkout to judge against"
    )
    common.add_argument(
        "--config",
        default="promptfoo/promptfooconfig.determ.yaml",
        help="determ suite config, relative to the target checkout",
    )
    common.add_argument(
        "--runner",
        default=os.environ.get("IMPROVE_RUNNER", ""),
        help="suite runner command; invoked as `<runner> <config> <output.json>` "
        "in the target checkout (Phase 6c supplies the pinned promptfoo wrapper)",
    )
    common.add_argument(
        "--cache", default="", help="baseline cache file (default: derived from --journal + target SHA)"
    )
    common.add_argument(
        "--coverage-mode",
        choices=COVERAGE_MODES,
        default=os.environ.get("IMPROVE_COVERAGE_MODE", "schema-path"),
        help="D3 added-value check: mutation (strong, needs --mutants-dir), "
        "schema-path (D3-lite, the default), or off (D1/D2 only)",
    )
    common.add_argument(
        "--mutants-dir",
        default=os.environ.get("IMPROVE_MUTANTS_DIR", ""),
        help="directory of mutant *.patch files against the target source "
        "(required for --coverage-mode mutation)",
    )

    bl = sub.add_parser(
        "baseline",
        parents=[common],
        help="compute/verify the reproducible baseline of the existing suite on HEAD",
    )
    bl.set_defaults(func=cmd_baseline)

    jd = sub.add_parser(
        "judge", parents=[common], help="judge one candidate diff (D1 + D2)"
    )
    jd.add_argument("--candidate", required=True, help="unified diff of the candidate")
    jd.set_defaults(func=cmd_judge)

    args = p.parse_args(argv)
    if not args.runner.strip():
        p.error("--runner is required (or set IMPROVE_RUNNER)")
    if args.coverage_mode == "mutation" and not args.mutants_dir.strip():
        p.error("--coverage-mode mutation requires --mutants-dir (or IMPROVE_MUTANTS_DIR)")
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
